# Site settings
course_name: Algorithms and Data Structures
course_description: "A course to introduce the zoology of Data structures and their use in use in Problem solving. The course will also teach you to the Design and analysis of algorithms."
course_semester: "Fall 2022"

baseurl: "/DataStructures/" # the subpath of your site, e.g. /blog/
url: "https://anassbelcaid.github.io" # the base hostname & protocol for your site

schoolname: "National School of Applied Sciences"
schoolurl: "http://www.ensas.uca.ma/"
twitter_username: anassBelcaid1

address: |
    National School of Applied Sciences
    Safi
    Morocco

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"

